version: '3'

services:
  backend-prod:
    image: dalpengholic/weatherapp_backend-prod:latest
    env_file: .prod.env
    ports:
      - '9000:9000'
    command: ["npm", "start"]

  frontend-prod:
    image: dalpengholic/weatherapp_frontend-prod:latest
    env_file: .prod.env
    ports:
      - '8000:8000'
    command: ["npm", "start"]
    depends_on:
      - backend-prod
